from typing import List

convert_to_wav: bool = True
midi_file_paths: List[str] = [
                              # "/Users/agear/Documents/Projects/AGM/percussion_test.mid",
                              # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aphids/Aphids2.mid",
                              # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/0.7/0.71.mid",
                              # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aleksei's Visions of Chess War/Aleksei's Visions of Chess War.mid",
                              # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Human Body (Can Run On Sugar Alone Goddamnit!)/The human body can run on sugar alone, God damn it!8.mid",
                              #
                                "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/fusion solo.mid",
                                "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Something I'm working onnow.mid",
                                "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Something I'm working onnow2.mid",
                                "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/newcooltingy.mid",
                                "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/gershwin_rhapsody.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Something I'm working on.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/wingfort.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Opeth/Credence.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Frank Zappa/legend.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Pantera/War Nerve.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/David Bowie/Life On Mars.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/David Bowie/Bowie, David - Memory Of A Free Festival.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Liquid Tension Experiment/paradigm_shift.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Liquid Tension Experiment/acid_rain.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Liquid Tension Experiment/biaxident.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Ozric Tentacles/Vibuthi.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Ozric Tentacles/chdon.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Ozric Tentacles/erpland.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Ozric Tentacles/Sunscape!.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Pink Floyd/dogs.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Pink Floyd/sheep.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Megadeth/05 - Countdown To Extinction/Skin O' My Teeth.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Dream Theater/05 - A Change Of Seasons/the_dance_of_eternity_solo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Dream Theater/05 - A Change Of Seasons/acos2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Dream Theater/05 - A Change Of Seasons/wfs-ltl.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Dream Theater/08 - Metropolis Pt 2 - Scenes From A Memory/The Dance Of Eternity.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Dream Theater/08 - Metropolis Pt 2 - Scenes From A Memory/Home.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Bands/Yes/CloseToTheEdge.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/G-Gb6-F.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/psychadelic fusion solo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Zip/Prog1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Zip/Prog.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/ishotthe.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/ipanema.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/heartof.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/rapture.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/oneluv.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/waiting.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/jammin.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/youway.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/love.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/nowoman.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/isthislo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Caribbean/redwine.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/icecap_act1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/maple leaf fag.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/FatalSolo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/triplets.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Chops/Tapping Exercises.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Chops/alternate picking.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Chops/Arpeggio Exercises.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Chops/Legato Exercises.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/random disembowlment of ethnic albainians.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises172-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises196-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/drinking wine/drinking wine.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises164-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/with groove.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Cool4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises180-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/If you dont know kick snare.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/Escuridão.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/Performance [reprise].mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/If you dont know side stick.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/I met a ghost2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/If you don't know where you're going, you'll wind up som (1).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/Kyyti.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/Kelvata4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/Music can express nothing but itself2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/Man created beauty to repress truth.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/Kyyti3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/If you don't know drums.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Neljä naista vetenä tulivat/If you don't know where you're going, you'll wind up somewhe.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Glistening Cobweb Slumber/Glitter & Sticker Stars4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Glistening Cobweb Slumber/Reflections In Drained Wine Glasses.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Glistening Cobweb Slumber/Dust Blown From A Cartrage.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Glistening Cobweb Slumber/Tears of Joy Washed Anxiety Away4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Glistening Cobweb Slumber/Gimmick 2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Glistening Cobweb Slumber/weird enough question mark.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Glistening Cobweb Slumber/dreams of corsica.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/enlightenment/androids.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/enlightenment/caffiene+pills+and+the+patch.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/enlightenment/scruffy5.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/enlightenment/advertisement4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/enlightenment/laconic.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/enlightenment/androids2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/Fractal Soul.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/the man who sold his teeth.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/Barefoot.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/bass3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/Aphids.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/my eyes swim like dolphins(bass).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/uix uix7.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/Fractal Soul2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/my eyes swim like dolphins.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/ugly children.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/following the candy trail (secanol).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/bass.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/wash.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/Climbing Up The Horizon.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/Post Three Days/This Doesn't Engage My Emotions At All.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/White Noise.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/Orbits.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/transparency.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/Orbit.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/Taking Days Off.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/brian eno's shaven head.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/Autoerotic Asphyxiation.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/[Bleak Skies].mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/Trance.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/00a/strobelight/Shaving Brian Eno's Head.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises156-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/ExSolo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/fruity projects/bassline.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/fruity projects/bassline2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Crash/Tangiers [Crash].mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Crash/tangiers.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Crash/Tangier.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Crash/Tangiers save.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Crash/Tangiers b.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Crash/Tangiers (newest).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Crash/Tangiers 2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Difficult.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Tangiers [Crash].mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Visions Of Chess War.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Androids.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Cannon Hill Park.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Chernobyl.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Nighttime Thoughts Of Brightly Lit Stairs.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Bleak Skies.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Climbing Up The Horizon1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Androids1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Climbing Up The Horizon.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/Shaving Brian Eno's Head.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Clonlara/George & the Star.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises108-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises140-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Fast1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises124-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Prog/Prog1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Prog/Prog.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises188-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Fast2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/frusciante/new frusciante.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/frusciante/unfinished.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/frusciante/what I'm working on2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/frusciante/what I'm working on.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises132-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Psychadelic/psychadelic color world.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Psychadelic/psychadelic color worldfast.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/New/New.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Heavy/Heavy.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Melting Butterflies/Circle Of Stones2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Melting Butterflies/Trippin'2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Melting Butterflies/Bleak Skies2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Melting Butterflies/Bleak Skies.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Melting Butterflies/Silver Silhouette.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Melting Butterflies/Circle Of Stones.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Melting Butterflies/Trippin'.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/West/sergio leone3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises148-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/With Groove/Froggod.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Funky/FunkedToDeath.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Funky/Basssolo2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Funky/FunkyGroove1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Funky/FunkyGroove.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Funky/Basssolo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises100-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises204-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/dancepunk/dancepunk.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/Fast.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/0Temp/chromatic speed exersises116-1000.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Warm up.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/cathy b flat major.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/cathysonate.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/jolene b flat major.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/jolene b flat major100.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/jolenesonate.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/Sonate.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/cathy b flat major100.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/b flat major100.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Mom & Cathy/b flat major.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Flamenco & jazz/solear_1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Flamenco & jazz/malagens.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Embraced.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/aquaticruin.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Guitar Pro Songs/Etude n°5.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Guitar Pro Songs/All in hands.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/04-On_That_Day.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/14-Jenova.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/15-Continue.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/07-Electric_de_Chocobo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/02-Ahead_On_Our_Way.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/19-Gold_Saucer.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/12-Difficult_To_Stand.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/10-Fortress_of_Condor.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/18-Mining_Town.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/11-Rufus_Ceremony.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/21-Sandy_Badlands.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/01-Main_Theme.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/09-Chasing.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/03-Goodnight.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/16-Costa_del_Sol.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/05-Farm_Boy.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/20-Cait_Sith.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/06-Waltz_de_Chocobo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 2/08-Cinco_de_Chocobo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/21-Great_Northern_Cave.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/15-Debut.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/20-Buried_In_the_Snow.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/22-Reunion.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/02-Life_Stream.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/09-Wutai.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/18-Cry_of_Planet.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/06-The_Nightmare.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/10-Stolen_Materia.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/04-Descendant_of_Shinobi.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/16-Interrupted.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/14-Tango_of_Tears.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/11-Racing_Chocobos.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/19-Aeris.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/01-Cosmo_Canyon.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/03-Great_Warrior.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/13-A_Great_Success.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/07-Cid.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/23-Who_Am_I.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/05-Those_Chosen_By_the_Planet.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/08-Steal_the_Tiny_Bronco.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/17-Forested_Temple.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 3/12-Fiddle_de_Chocobo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/13-Judgement_Day.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/05-Parochial_Town.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/02-Weapon_Raid.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/10-Countdown_Begins.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/03-Highwind.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/01-Full_Scale_Attack.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/06-Edge_of_Despair.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/11-If_You_Open_Your_Heart.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/16-One_Winged_Angel.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/14-Jenova_Absolute.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/15-Birth_of_God.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/17-World_Crisis.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/12-Makou_Cannon.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/07-Other_Side_of_Mountain.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/18-Staff_Roll.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/09-Sending_A_Dream.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/04-Deep_Sea.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 4/08-Hurry_Faster.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/22-Crazy_Motorcycle.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/11-Fanfare.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/10-Fighting.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/18-Don_Slums.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/15-Oppressed.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/02-Opening.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/13-Turks.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/19-Infiltrating.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/08-Lurking.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/03-Makou_Reactor.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/07-Hurry.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/21-RedXIII.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/06-Barret.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/14-Rotting_Pizza.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/01-Prelude.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/23-Holding_My_Thoughts.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/04-Anxious_Hearts.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/20-Still_More_Fighting.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/05-Tifa.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/12-Flowers.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/09-Shinra_Co.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/Disc 1/16-Honeybee_Manor.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/From CD/Guitar pro mix and match/Finaly Fantasy/19-Aeris.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Peeping Janet/Peeping Janet.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Suggest a Good Name (And That's What I'll Call It)/suggest a good name and that's what i'll call it (release ve.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Toy/Toy.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannonhill Park.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/tsss.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannonhill Park3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannonhill Park2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannon Hill Park.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannon Hill Park (tux).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/The Kaleidoscope Trumpet Brothers.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannon Hill Park Finale.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannon Hill Park2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannon Hill Park3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cannon Hill Park/Cannon Hill Park1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/A Socialite's Winter In  Uptown New York/A Socialite's Winter In Uptown New York.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Effigy/New Part/new part....mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Effigy/a new song to work with.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/I Met A Ghost/I met a ghost2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Warmer Than It Seems/Warmer Than It Seems.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Ripping Off The Fall/ripping off the fall.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Orbit/Orbit2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Archetype/The Archetype2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Derailed/derailed.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Derailed/derailed (long).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Transparency/Transparency3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Intermission/Intermission.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Audition/Audition.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Luddites, the Lot of Them/Luddites, the lot of them.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Laconic/(pre)laconic/(pre)laconic.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Laconic/laconic.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Dance of the Frog God/Frog God Electro2 short.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Music Can Express Nothing But Itself/Music can express nothing but itself2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Pollen/Pollen.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Laughtrack/laughtrack.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Man They Hang Upside Down/The Man They Hung Upside Down.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Man They Hang Upside Down/The Man They Hang Upside Down.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Man They Hang Upside Down/The Man They Hang Upside Down (tux).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/My Eyes Swim Like Dolphins/My Eyes Swim Like Dolphins3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Let Your People Fry/let your people fry.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Scruffy/scruffy5.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Jumbo Jet/Jumbo Jet.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cherish/Cherish.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Autumnal Girl/Autumnal Girl2 (square).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Autumnal Girl/Autumnal Girl2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/M-Brane/m-brane.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Tears of Joy Washed Anxiety Away/Tears of Joy Washed Anxiety Away4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Ferris Wheel/Ferris Wheel2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Stranger Little Things/stranger little things.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Standing In The Backyards/standing in the backyards.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Escuridão/Escuridão.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cat Tail/cat tail.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Introduction/Introduction.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Weird Enough Question Mark/weird enough question mark.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Gimmick/Gimmick 2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Ending Slip/ending slip for finale.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Ending Slip/ending slip.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Luv 2 Kitty (w_ Trendy Shades)/Luv To Kitty (w_ Trendy Shades)2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Trance/Trance.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Just To Soak A Bit Of You Up/just to soak a bit of you up.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aphids/Aphids2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Oi Makara/oi makara2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Performance [Reprise]/Performance [reprise].mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Performance [Reprise]/performance/performance.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Kaupalle/Kaupalle.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Ketamine Emma/Ketamine Emma.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Nighttime Thoughts Of Brightly Lit Stairs/Nighttime Thoughts Of Brightly Lit Stairs2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Dance Like We're Joy Division/dance like we're joy division.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Sprout Wings and Fly (In Purple and Golden Clouds)/Sprout wings and fly in purple and golden clouds.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Homunculi/homunculi.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aerobody Toothbrush/Aerobody toothbrush.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Indian Penny Pop Recycle/indian penny pop recycle2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/If You Don't Know Where You're Going (You Might End Up Somewhere Else)/If you don't know where you're going, you'll wind up somewhere else.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Say What You Mean/say what you 2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Small Town In America/small town in america (release version).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Small Town In America/Delay section/delay section2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Morphine Lobotomy/Morphine Lobotomy3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Climbing Up The Horizon/Climbing Up The Horizon for finale.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Climbing Up The Horizon/Climbing Up The Horizon (arranged and named).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Climbing Up The Horizon/Climbing Up The Horizon.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Climbing Up The Horizon/Climbing Up The Horizon (arranged and named2).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cleatus and the Tumbleweed/Cleatus and the Tumbleweed.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Boylston Street/Boylston Street.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Leave The Sun Behind/Leave The Sun Behind.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Kyyti/Kyyti3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aleksei's Visions of Chess War/Visions Of Chess War.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aleksei's Visions of Chess War/synth wash.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aleksei's Visions of Chess War/Aleksei's Visions of Chess War for finale.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aleksei's Visions of Chess War/Visions Of Chess War2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aleksei's Visions of Chess War/Aleksei's Visions of Chess War.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Aleksei's Visions of Chess War/Aleksei's Visions Of Chess War (tux).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Dust Blown From A Cartrage/Dust Blown From A Cartrage.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Moomin Castle/Moomin castle.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Glitter & Sticker Stars/Glitter & Sticker Stars4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Anniversary Song/Anniversary song2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Caffiene Pills and the Patch/Caffiene Pills and the Patch.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Man Who Sold His Teeth/the man who sold his teeth.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Man created beauty to repress truth/Man created beauty to repress truth2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Epic/Epic Part/epic part.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Epic/epic.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Don't Give Me SARS/Don't Give Me SARS.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Don't Give Me SARS/New Don't Give Me SARS/new dont give me sars.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Topographic Tales of Expendable Friends /topographic tales of expendible friends.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Shakespeare Tears His Eyes Out/shakespeare tears his eyes out.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Behind A Rocky Crag (In An Underwater Cave)/Behind A Rocky Crag (In An Underwater Cave).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Creepy Crawly Claymation Wizard of Oz/creepy crawly claymation wizard of oz.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Fractal Soul/Fractal Soul.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Fractal Soul/Fractal Soul for finale.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Wallflowers and deadlight/Wallflowers and deadlight.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Find In You/Find In You2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Pots and Pans/Pots and pans.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Chords of Nature/Chords Of Nature2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Reflections In Drained Wine Glasses/Reflections In Drained Wine Glasses.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Amputate/Amputate.mid_ch1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Amputate/Amputate.mid_ch3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Amputate/Amputate.mid_ch2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Amputate/Amputate.mid_ch5.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Amputate/Amputate.mid_ch4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Amputate/Amputate.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Membraneous Slime Wall/Membraneous Slime Wall.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Taking The Day Off/Taking Days Off.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Beauty Spot/Beauty Spot3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Dreams of Corisca/dreams of corsica.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/We Used To Rule This Town/We used to rule this town2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/White Noise/White Noise.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Tick Tock/Tick Tock.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Lizard in the Mirror/The Lizard In The Mirror.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Shaving Brian Eno's Head/Shaving Brian Eno's Head2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Following the Candy Trail (Secanol)/following the candy trail (secanol).mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Advertisement/advertisement4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/George & the Star/fragment/fragment.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/George & the Star/George Jung & the Christmas Star Special3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/For a cow to know that it's higher purpose was to be eaten would probably not satisfy it/For a cow to know that its higher purpose was to be eaten would probably not satisfy it.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/I Need You So-Oh-Oh Badly/i need you so-oh-oh badly.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Autoerotic Asphyxiation/Autoerotic Asphyxiation.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/If You're Running Go That Way!/I'd Run Away.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/If You're Running Go That Way!/I'll Run Away/I'll Run Away.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/PTSD/PTSD.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Violet Threads/violet threads solo.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Androids/androids2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Modern Blues/modern blues.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/I Think I Wanna Sweep You Off Your Feet/i think i wanna sweep you off your feet2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Kelvata/Kelvata4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Proteine 1-A5/Proteine 1-A5.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/This Doesn't Engage My Emotions At All/This Doesn't Engage My Emotions At All3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/This Doesn't Engage My Emotions At All/This Doesn't Engage My Emotions At All4/This Doesn't Engage My Emotions At All4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/0.7/0.71.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Ugly Children/We'd Have Ugly Children1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Scrawling In Journals/scrawling in journals.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Bleak Skies/[Bleak Skies3].mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch6.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch7.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch5.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch4.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch10.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch9.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Barefoot/Barefoot.mid_ch8.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Pocket Full Of Posies/Pocket Full Of Posies.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Cosmique/cosmique5.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/Chernobyl/Chernobyl2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/For A Limited Time Only/For A Limited Time Only3.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Human Body (Can Run On Sugar Alone Goddamnit!)/The human body can run on sugar alone, God damn it!8 Named.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Human Body (Can Run On Sugar Alone Goddamnit!)/The human body can run on sugar alone, God damn it!8.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Finished/The Painting Drips Onto My Floor/The Painting Drips Onto My Floor.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Progjazz2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/on a day like today.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/something stirred today.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/uix uix7.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/altruism.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/pensive.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/auxilliary langauge.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/nana nana na na.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Sokeri ja muru1.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Escape From The War Zone2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Trippin'.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/naïve.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Linja Auto Turruun.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Geek Glasses in the Rockies.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/onni is warm h.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/canadian koff syrup.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/peer pressure2.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Ol' Timer Home.mid",
                                # "/Users/agear/Documents/Projects/AGM/Guitar Pro PDFs/Unfinished/Sycamore Seeds Twirling Towards An Idylic Deep South River.mid",
                              ]
